name: randomizer
description: Randomize creation of PUBG teams

publish_to: "none"
version: 2.2.0+5

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
